import type { NextConfig } from "next";

// During local `wrangler dev` / `cf:preview` the Cloudflare runtime is
// available to server components via `getCloudflareContext()`. Importing
// this init module is a no-op in production Workers but makes the bindings
// (KV, R2, etc.) reachable during local dev. Safe to leave in place.
import { initOpenNextCloudflareForDev } from "@opennextjs/cloudflare";
initOpenNextCloudflareForDev();

const nextConfig: NextConfig = {
  reactCompiler: true,

  // next/image: skip Next's built-in optimizer. cdn.brighttv.co.th already
  // serves WebP at multiple sizes generated by WP, and enabling the Next
  // optimizer on Workers requires a Cloudflare Images binding (hence the
  // `env.IMAGES binding is not defined` warning in wrangler tail). With
  // `unoptimized: true`, <Image> renders a plain <img> pointing at the
  // upstream URL — no /_next/image route, no IMAGES binding needed.
  images: {
    unoptimized: true,
    remotePatterns: [
      { protocol: "https", hostname: "cdn.brighttv.co.th" },
      { protocol: "https", hostname: "www.brighttv.co.th" },
      { protocol: "https", hostname: "brighttv.co.th" },
      { protocol: "https", hostname: "secure.gravatar.com" },
    ],
  },
};

export default nextConfig;
